tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - grycap_custom_types: https://raw.githubusercontent.com/grycap/tosca/devel/custom_types.yaml

description: Deploy a Galaxy Server using a local LRMS.

metadata:
  template_version: "1.0.0"
  template_name: Galaxy
  display_name: Deploy a Galaxy portal
  icon: images/galaxy.png
  tabs:
    Galaxy Data: .*
  parents:
    - simple-node-disk.yml

topology_template:

  inputs:

    admin_email:
      type: string
      description: Email of the Galaxy admin user
      default: admin@admin.com
    admin_password:
      type: string
      description: Password of the Galaxy admin user
      default: adminpass

    dns_name:
      type: string
      description: DNS name of the Galaxy portal
      default: ''

  node_templates:

    galaxy_portal:
      type: tosca.nodes.indigo.GalaxyPortal
      capabilities:
        endpoint:
          properties:
            ports:
              https:
                protocol: tcp
                source: 443
              http:
                protocol: tcp
                source: 80
      properties:
        admin_email: { get_input: admin_email }
        admin_password: { get_input: admin_password }
        dns_name: { get_input: dns_name }
      requirements:
        - lrms: local_lrms
        - host: simple_node

    # type to describe a Galaxy not using any LRMS but using the local system
    local_lrms:
      type: tosca.nodes.indigo.LRMS.FrontEnd.Local
      requirements:
        - host: simple_node

  outputs:
    galaxy_url:
      value: { concat: [ 'https://', get_attribute: [ simple_node, public_address, 0 ], ':8443/' ] }
