---
- hosts: localhost
  connection: local
  vars:
    username: "{{ user | default(ansible_user) }}"
  tasks:
    - name: Add the authorized_key to the nodes
      authorized_key:
        user: "{{ username }}"
        key: "{{ item }}"
      loop: "{{ ssh_keys }}"
